# Generated by Django 4.2.3 on 2023-07-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dietas_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paciente", old_name="criados", new_name="criado",
        ),
    ]
