# Generated by Django 4.2.3 on 2023-07-27 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dietas_app", "0002_rename_criados_paciente_criado"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado", models.DateField(auto_now_add=True, verbose_name="Criação")),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "peso",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Peso"
                    ),
                ),
                (
                    "proteina",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Proteina"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Refeicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado", models.DateField(auto_now_add=True, verbose_name="Criação")),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "refeicoes",
                    models.CharField(max_length=30, verbose_name="Refeições"),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Medida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado", models.DateField(auto_now_add=True, verbose_name="Criação")),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "peso",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Peso"
                    ),
                ),
                (
                    "altura",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Altura"
                    ),
                ),
                (
                    "nome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dietas_app.paciente",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Dietas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado", models.DateField(auto_now_add=True, verbose_name="Criação")),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Quantidade"
                    ),
                ),
                (
                    "alimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dietas_app.alimento",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dietas_app.paciente",
                    ),
                ),
                (
                    "refeicoes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dietas_app.refeicao",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
