# Generated by Django 4.2.3 on 2023-08-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dietas_app", "0004_alter_dietas_quantidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alimento",
            name="peso",
            field=models.DecimalField(
                decimal_places=3, max_digits=15, verbose_name="Peso"
            ),
        ),
        migrations.AlterField(
            model_name="alimento",
            name="proteina",
            field=models.DecimalField(
                decimal_places=3, max_digits=15, verbose_name="Proteina"
            ),
        ),
        migrations.AlterField(
            model_name="dietas",
            name="quantidade",
            field=models.IntegerField(verbose_name="Quantidade"),
        ),
    ]
